FROM python:3.7-slim

RUN mkdir /opt/MyStreet

RUN python -m pip install --upgrade pip

RUN python -m pip install poetry
WORKDIR /opt/MyStreet

COPY poetry.lock .
COPY pyproject.toml .

RUN poetry install --no-root -vvv


ENTRYPOINT ["poetry"]
